#!/usr/bin/bash

src="/home"
dest="/backup"
date=$(date +%Y-%M-%D)
backup_dir="$dest/$date"

mkdir -p "$backup_dir"


rsync -av "$src" "$backup_dir"

if [ $? -eq 0 ];
then
    echo "backup success"
else
    echo "backup Failed"
fi
